version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    # command: gunicorn specialworld.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./backend:/app
    expose:
      - "8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    expose:
      - "5173"
    restart: unless-stopped
    networks:
      - app-network

  proxy:
    build: ./nginx
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#   static_volume:
#   media_volume:
