version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    # command: gunicorn specialworld.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./backend:/app
    expose:
      - "8000"
    environment:
      - DB_HOST=database_service_name
      - DB_NAME=your_db_name
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - app-network

  proxy:
    build: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#   static_volume:
#   media_volume:
